# training hyper-parameters
num_epochs : 300
batch_size : 32
dropout_keep_prob : 0.5
clip_value : 10
learning_rate : 0.0004
l2 : 0.0
seq_length : 30
optimizer : adam
early_stop_step : 50

# embeddings hyper-parameters
threshold : 0
embedding_size : 100
embedding_normalize : 1

# layers hyper-parameters
hidden_size : 300
attention_size : 300

# report hyper-parameters
eval_batch : 1000


## reports
save_path : ./model/checkpoint
best_path : ./model/bestval
log_path : ./config/log/log
tfboard_path : ./tensorboard

## config
config_path : ./config/config.yaml